export const cards = [
  {
    id: 1,
    name: "Slime",
    rarity: "common",
  },
  {
    id: 2,
    name: "Fire Slime",
    rarity: "common",
    element: "fire",
  },
  {
    id: 3,
    name: "Earth Slime",
    rarity: "common",
    element: "earth",
  },
  {
    id: 4,
    name: "Water Slime",
    rarity: "common",
    element: "water",
  },
  {
    id: 5,
    name: "Holy Slime",
    rarity: "common",
    element: "holy",
  },
  {
    id: 6,
    name: "Dark Slime",
    rarity: "common",
    element: "dark",
  },
  {
    id: 7,
    name: "Mercenary A",
    rarity: "common",
  },
  {
    id: 8,
    name: "Mercenary B",
    rarity: "common",
  },
  {
    id: 9,
    name: "Town Guard A",
    rarity: "common",
  },
  {
    id: 10,
    name: "Town Guard B",
    rarity: "common",
  },
  {
    id: 11,
    name: "Town Guard C",
    rarity: "common",
  },
  {
    id: 12,
    name: "Skeleton Warrior A",
    rarity: "common",
  },
  {
    id: 13,
    name: "Skeleton Warrior B",
    rarity: "common",
  },
  {
    id: 14,
    name: "Dark Crow",
    rarity: "common",
    element: "dark",
  },
  {
    id: 15,
    name: "Ancient Owl",
    rarity: "common",
  },
  {
    id: 16,
    name: "Chicken",
    rarity: "common",
  },
  {
    id: 1001,
    name: "Fire Wisp",
    rarity: "uncommon",
    element: "fire",
  },
  {
    id: 1002,
    name: "Earth Wisp",
    rarity: "uncommon",
    element: "earth",
  },
  {
    id: 1003,
    name: "Water Wisp",
    rarity: "uncommon",
    element: "water",
  },
  {
    id: 1004,
    name: "Baetylus",
    rarity: "uncommon",
    element: "fire",
  },
  {
    id: 1005,
    name: "Black Roc",
    rarity: "uncommon",
  },
  {
    id: 1006,
    name: "Earth Priestess",
    rarity: "uncommon",
    element: "earth",
  },
  {
    id: 1007,
    name: "Fire Priestess",
    rarity: "uncommon",
    element: "fire",
  },
  {
    id: 1008,
    name: "Water Priestess",
    rarity: "uncommon",
    element: "water",
  },
  {
    id: 1009,
    name: "Mimic",
    rarity: "uncommon",
    element: "dark",
  },
  {
    id: 1010,
    name: "King Arthur",
    rarity: "uncommon",
    element: "holy",
  },
  {
    id: 1011,
    name: "Shark Warrior",
    rarity: "uncommon",
    element: "water",
  },
  {
    id: 1012,
    name: "Tricorn",
    rarity: "uncommon",
  },
  {
    id: 2001,
    name: "Earth Wolf",
    rarity: "rare",
    element: "earth",
  },
  {
    id: 2002,
    name: "Fire Wolf",
    rarity: "rare",
    element: "fire",
  },
  {
    id: 2003,
    name: "Water Wolf",
    rarity: "rare",
    element: "water",
  },
  {
    id: 2004,
    name: "Brown Roc",
    rarity: "rare",
  },
  {
    id: 2005,
    name: "Wild Hippo",
    rarity: "rare",
    element: "water",
  },
  {
    id: 2006,
    name: "Wild Board",
    rarity: "rare",
    element: "earth",
  },
  {
    id: 2007,
    name: "Corrupted Shark",
    rarity: "rare",
    element: "dark",
  },
  {
    id: 2008,
    name: "Life Reaper",
    rarity: "rare",
    element: "holy",
  },
  {
    id: 3001,
    name: "Gemstone Dragon Fire",
    rarity: "epic",
    element: "fire",
  },
  {
    id: 3002,
    name: "Gemstone Dragon Water",
    rarity: "epic",
    element: "water",
  },
  {
    id: 3003,
    name: "Gemstone Dragon Earth",
    rarity: "epic",
    element: "earth",
  },
  {
    id: 3004,
    name: "Hoarfrost Hind",
    rarity: "epic",
  },
  {
    id: 4001,
    name: "Sacred Beast Polar Bear",
    rarity: "legendary",
    element: "water",
  },
  {
    id: 4002,
    name: "Sacred Beast Tiger",
    rarity: "legendary",
    element: "fire",
  },
];
